config/routes.rb
Votevote::Application.routes.draw do
  unauthenticated :user do
    root :to => 'home#index'
  end
#  unauthenticated do
    #devise_scope :user do
     #root :to => "devise/registrations#new"
    #end
  #end
  devise_for :users
  resources :users
  
  # controller matchers
  get '/bill', :to => 'bills#find', :as => :find_bill
  get '/bills/:id', :to => 'bills#show', :as => :bill
  get '/votes/:id', :to => 'votes#show', :as => :vote
  get '/vote', :to => 'votes#find', :as => :find_vote
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recent_votes = Vote.get_recent_votes('senate')
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
.home
  %h1 
    reVoter
    
  %h2.sub-head
    \:reImagine the US Senate
  <br />

  %p 
    %strong
      The US Senate is undermining American democracy. One import way this is happening is through the enormous power given to a handful of sparsly populated states.
      <br />
      <br />
      Because each states gets the same number of Senators, people in larger states have relatively less power in the federal government then those from smaller states. This compromise might have made sense at our nation's founding, when the largest state (Virginia) had just over ten times the population of the smallest state (Kentucky).
      <br />
      <br />
      Today the largest states, California, with 38 million people and Texas, with 26 million, have 65 times and 45 times the residents of Wyoming or Vermont with around 0.6 million each. Want to see how votes in the Senate would change if each citizen had equal representation?
      <br />
      <br />
      Then fill in the information below to find a bill you're interested in. From there, select a vote and see how more equal representation would change what gets voted into law!
  <br />

  %h2.center
    Find a Bill

  = form_tag( {:controller => :bills, :action => :find}, :method => :get ) do
    = radio_button_tag :bill_type, "s", {:checked => true}
    = label_tag "Senate Bill"
    &nbsp;
    = radio_button_tag :bill_type, "sres"
    = label_tag "Senate Resolution"
    <br />

    = label_tag "Congress"
    = select_tag :congress, options_for_select( CONGRESSES, 113 )
    <br />

    = label_tag "Number"
    = tag :input, type: :text, name: :bill_number, id: :bill_number, pattern: "[0-9]+", required: true, placeholder: ''
    <br />
    <br />
    
    = submit_tag "Get It!", :id => 'submit-button', :class => 'btn'
  //<br />

  %h2.center
    Recent Senate Votes

  %ul
    - @recent_votes.each do |v|
      %li.recent-vote
        = link_to v["question"], find_vote_path( {roll_id: v["roll_id"]} )

:javascript

  var bodyAjax = ( function() {

      var ajaxLink = function( element ) {
              $link = $( element );
              href = $link.attr( 'href' );
              $.get( href ).success( function( result ) {
                  bodyAjax.switchBody( result );
              });
      };  

      var switchBody = function( result ) { 
              newBody = $.parseHTML( result, document, true );
              oldBody = $( 'body' );
              oldBody.html( newBody );
      };

      return {
          ajaxLink: ajaxLink,
          switchBody: switchBody
      };
  })();

  $( document ).ready( function() {

    history.replaceState( {path: '/'}, '', '/' );

    var ajax = ( function() {
      var billNumberElement = $( '#bill_number' );

      var formSubmit = function() {
      var billNumberValue = $( '#bill_number' ).val();
      var billType = $( 'input:radio[name=bill_type]:checked' ).val();
      var congress = $( '#congress' ).val();

        $.get( '#{find_bill_url}', { bill_type: billType, bill_number: billNumberValue, congress: congress } )
        .success( function( result ) {
          bodyAjax.switchBody( result );
        })
        .fail( function( result ) {
          if (result.resultText =~ /NoMethodError at \/bill/)
            billNumberElement[0].setCustomValidity( "drats! no luck finding it :-/" );
            billNumberElement.val( '' );
            billNumberElement.attr( 'placeholder', "drats! no luck finding it :-/" );
        });
      };

      $( '#submit-button' ).click( function( event ) {
        event.preventDefault();
        billNumberFeedback();
        if ( billNumberElement[0].validity.valid === true ) {
          formSubmit();
          history.pushState( {path: '/'}, '', '/' );
        }
      });

      var billNumberFeedback = function() {
        
        if ( billNumberElement[0].validity.patternMismatch === true ) {
          billNumberElement[0].setCustomValidity( 'please feed me numbers :-)' );
          billNumberElement.val( '' );
          billNumberElement.attr( 'placeholder', 'please feed me numbers :-)' );
          }
        else if ( billNumberElement[0].validity.valueMissing === true ) {
          billNumberElement[0].setCustomValidity( 'I\'m hungry :-)' );
          billNumberElement.attr( 'placeholder', 'I\'m hungry :-)' );
          }
        else 
          billNumberElement[0].setCustomValidity( '' );
      };
   })();
  });