config/routes.rb
Votevote::Application.routes.draw do
  unauthenticated :user do
    root :to => 'home#index'
  end
#  unauthenticated do
    #devise_scope :user do
     #root :to => "devise/registrations#new"
    #end
  #end
  devise_for :users
  resources :users
  
  # controller matchers
  get '/bill', :to => 'bills#find', :as => :find_bill
  get '/bills/:id', :to => 'bills#show', :as => :bill
  get '/votes/:id', :to => 'votes#show', :as => :vote
  get '/vote', :to => 'votes#find', :as => :find_vote
end

app/models/bill.rb
class Bill < ActiveRecord::Base

  serialize :nicknames
  serialize :vote_list
  serialize :urls
  serialize :last_action

  attr_accessible :sun_bill_id, 
            :last_action, 
            :last_vote_at, 
            :nicknames, 
            :official_title, 
            :summary_short, 
            :vote_list, 
            :urls

  has_many :votes

  validates_uniqueness_of :sun_bill_id
  validates_presence_of :official_title, :summary_short, :sun_bill_id

  def self.get_bills sun_bill_id_array
    bill_list = []
    sun_bill_id_array.each do | id |
      bill = self.find_or_initialize_by_sun_bill_id( id )
      if bill.new_record?
        bill = self.create_bill( bill, id )
      end
      bill_list << bill
    end
    bill_list
  end

  def self.create_bill bill, sun_bill_id
    api = CongressApi.new
    results = api.get_bill( sun_bill_id )
    results = results[ "results" ][0]
    bill.official_title = results[ "official_title" ] 
    bill.nicknames = results[ "nickname" ] 
    bill.summary_short = results[ "summary_short" ] 
    bill.last_vote_at = results[ "last_vote_at" ] 
    bill.last_action = results[ "last_action" ] 
    bill.vote_list = results[ "votes" ]
    bill.urls = results[ "urls" ]
    bill.save
  end

end

app/controllers/bills_controller.rb
class BillsController < ApplicationController

  def find
    sun_bill_id = [params[:bill_type] + params[:bill_number] + "-" + params[:congress]]
    bill = Bill.get_bills(sun_bill_id)
    @bill = bill[0]
    vote_array =[]
    @bill.vote_list.each do |vote|
      vote_array << vote["roll_id"]
    end
    @votes = Vote.get_votes(vote_array)
    render :show
  end

  def show
    @bill = Bill.find(params[:id])
    @votes = @bill.votes
  end

end

app/views/bills/show.html.haml
.bill
  %h1
    = @bill.official_title

  %p
    = @bill.summary_short

  %h1
    - if !@votes.blank?
      Votes
    - else
      No votes yet

  %ul
    - @votes.each do |vote|
      %li
        = link_to("#{vote['question']} (#{vote['result']}, #{vote['breakdown']['total']['Yea']} - #{vote['breakdown']['total']['Nay']})", vote_path(vote.id), method: :get, remote: true)

:javascript

  var bodyAjax = (function() {

      var ajaxLink = function( element ) {
              $link = $( element );
              href = $link.attr( 'href' );
              $.get( href )
              .success( function( result ) {
                  bodyAjax.switchBody( result );
              });
      };  

      var switchBody = function( result ) { 
              newBody = $.parseHTML( result, document, true );
              oldBody = $( 'body' );
              oldBody.html( newBody );
      };

      return {
          ajaxLink: ajaxLink,
          switchBody: switchBody
      };
  })();

  $( document ).ready( function() {

    history.replaceState( {path: '#{bill_path(@bill)}'}, '', '#{bill_path(@bill)}' );
    document.title = ('#{@bill.official_title}');

    var voteLinks = (function() {
      
      $('a').on( 'click', function(e) {
        bodyAjax.ajaxLink( e.target );
        var href = $( this ).attr( 'href' );
        history.pushState( {path: href}, '', href );
        return false
      });
    })();
  });
  